# Generated by Django 6.0.2 on 2026-02-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_stocksucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
    ]
