# Generated by Django 6.0.2 on 2026-02-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ganancia',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
